services:
  - type: web
    name: stadium-booking-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PAYMENT_CARD
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PHONE
        sync: false
      - key: TZ
        value: Asia/Tashkent

